# ansible-playbook -u pi -k -i 'TARGET-DHCP-IP,' lockdown.yml
---

- name: Application server specific playbook
  hosts: all
  become: yes
  roles:
     - set-hostname
     - create-user
     - disable-passwords
     - expand-filesystem

  vars_prompt:
    - name: "hostname"
      prompt: "Hostname"
      private: no
    - name: "username"
      prompt: "User name"
      private: no
    - name: "password"
      prompt: "Password"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
    - name: "comment"
      prompt: "Username description"
      private: no
    - name: "public_key"
      prompt: "Path to public SSH key"
      private: no
